#!/usr/bin/env python3
"""Page to Stage build pipeline. Single source of truth: _build/events.json.
Run from the deploy root after editing events.json:  python3 _build/build_pts.py
Steps:
  1. (re)generate the 10 event pages at /page-to-stage/<slug>
  2. sync Page to Stage entries into calendar-events.json (idempotent)
  3. reminder: sitemap + hub grid are regenerated by their own generators when slugs change
The calendar sync is idempotent (it clears prior Page-to-Stage rows and rebuilds),
so adding/editing an event and re-running keeps the calendar correct automatically."""
import subprocess, sys, pathlib
HERE = pathlib.Path(__file__).resolve().parent
def run(p):
    print(f"\n>>> {p}")
    subprocess.run([sys.executable, str(HERE/p)], check=True)
run("gen_event_pages.py")        # event pages
run("sync_calendar_pts.py")      # calendar
print("\nPage to Stage build complete. Re-zip and deploy.")
